capstone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("solution.urls")),
    # path("__reload__/", include("django_browser_reload.urls")),
    # path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # type: ignore
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # type: ignore

solution/api/urls.py
from django.urls import path
from drf_spectacular.views import SpectacularSwaggerView, SpectacularAPIView

from solution.api import api_views

app_name = "api"

urlpatterns = [
    path("", api_views.api_root, name="api-root"),
    path("roles", api_views.roles, name="roles"),
    path("job-data", api_views.job_data, name="job-data"),
    path("worker-account", api_views.WorkerAccountView.as_view(), name="worker-account"),
    path(
        "worker-account/<str:username>",
        api_views.WorkerAccountView.as_view(),
        name="worker-account",
    ),
    path("employer-account", api_views.EmployerAccountView.as_view(), name="employer-account"),
    path(
        "employer-account/<str:username>",
        api_views.EmployerAccountView.as_view(),
        name="employer-account",
    ),
    path("change-password", api_views.ChangePasswordView.as_view(), name="change-password"),
    path("schema", SpectacularAPIView.as_view(), name="schema"),
    path("docs", SpectacularSwaggerView.as_view(url_name="solution:api:schema"), name="swagger-ui"),
]

solution/urls.py
from django.urls import include, path, re_path

from solution import views

app_name = "solution"


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("register", views.RegisterView.as_view(), name="register"),
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.logout_view, name="logout"),
    path("solution-api/", include("solution.api.urls")),
]

react_root = [
    # Match every url, except if starts with "media" or "static"
    re_path(
        r"^(?!admin|media|static|__reload__|__debug__)",
        views.IndexView.as_view(),
        name="react_root",
    )
]

urlpatterns = urlpatterns + react_root
# urlpatterns = format_suffix_patterns(urlpatterns)

solution/models.py
from __future__ import annotations

import uuid
from datetime import date
from typing import TYPE_CHECKING

import orjson
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core import validators
from django.core.validators import MinValueValidator
from django.db import models
from django.forms import JSONField
from django.utils.translation import gettext_lazy as _

from solution import validators as app_validators
from solution.utils import employer_logo_path, employer_photo_path, worker_account_path

file_validator = app_validators.FileValidator(max_size=3, content_types=("image/jpeg", "image/png"))

if TYPE_CHECKING:
    from django.db.models import Manager


def get_company_size():
    with open(settings.BASE_DIR / "solution/frontend/static-data/companySizes.json") as f:
        return orjson.loads(f.read())


class User(AbstractUser):
    id: int

    worker_account: Manager[WorkerAccount]
    employer_account: Manager[EmployerAccount]

    first_name = models.CharField(
        blank=True, max_length=20, validators=[validators.MinLengthValidator(2)]
    )
    last_name = models.CharField(
        blank=True, max_length=20, validators=[validators.MinLengthValidator(2)]
    )
    birthdate = models.DateField(
        blank=True, null=True, validators=[app_validators.validate_birthdate]
    )
    phone = models.CharField(
        blank=True,
        max_length=20,
        validators=[validators.RegexValidator(r"^(\d{1,3})(\d{2})(\d{9})$")],
    )
    verified_id = models.BooleanField(default=False)
    has_worker_account = models.BooleanField(default=False)
    has_employer_account = models.BooleanField(default=False)


class BaseModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.__repr__()


class Profession(BaseModel):
    id: int

    professionals: Manager[WorkerAccount]

    name = models.CharField(max_length=255)

    def __repr__(self) -> str:
        return f"{self.name}"


class JobType(BaseModel):
    id: int

    name = models.CharField(max_length=255)

    def __repr__(self) -> str:
        return f"{self.name}"


class Shift(BaseModel):
    id: int

    name = models.CharField(max_length=255)

    def __repr__(self) -> str:
        return f"{self.name}"


class DaysSchedule(BaseModel):
    id: int

    name = models.CharField(max_length=255)

    def __repr__(self) -> str:
        return f"{self.name}"


class JobTag(BaseModel):
    id: int

    name = models.CharField(max_length=255)

    def __repr__(self) -> str:
        return f"{self.name}"


class WorkerAccount(BaseModel):
    applied_jobs: Manager[Job]
    jobs: Manager[Job]
    received_feedbacks: Manager[EmployerFeedback]
    job_feedbacks: Manager[WorkerFeedback]
    signed_contracts: Manager[Contract]

    user_id: int
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="worker_account",
        primary_key=True,
    )
    photo = models.ImageField(
        blank=True, upload_to=worker_account_path, validators=[file_validator]
    )
    profession_id: int
    profession = models.ForeignKey(
        to=Profession, on_delete=models.CASCADE, related_name="professionals"
    )
    first_name = models.CharField(max_length=20, validators=[validators.MinLengthValidator(2)])
    last_name = models.CharField(max_length=20, validators=[validators.MinLengthValidator(2)])
    birthdate = models.DateField(validators=[app_validators.validate_birthdate])
    phone = models.CharField(
        max_length=20, validators=[validators.RegexValidator(r"^(\d{1,3})(\d{2})(\d{9})$")]
    )
    rating = models.IntegerField(
        default=0, validators=[validators.MinValueValidator(0), validators.MaxValueValidator(5)]
    )
    location = models.CharField(max_length=50)
    about = models.CharField(blank=True, max_length=255)
    verified_id = models.BooleanField(default=False)
    driving_license = models.BooleanField(default=False)
    last_update = models.DateTimeField(auto_now=True)

    @property
    def review_count(self) -> int:
        return self.received_feedbacks.count()

    @property
    def jobs_done(self) -> int:
        return self.jobs.filter(done=True).count()

    def __repr__(self) -> str:
        return f"{self.user_id} - {self.profession}"


class EmployerAccount(BaseModel):
    worker_feedbacks: Manager[EmployerFeedback]
    received_feedbacks: Manager[WorkerFeedback]
    contracts: Manager[Contract]

    user_id: int
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="employer_account",
        primary_key=True,
    )
    # Company Data
    logo = models.ImageField(blank=True, upload_to=employer_logo_path, validators=[file_validator])
    company_name = models.CharField(max_length=50)
    address = models.CharField(max_length=255)
    legal_name = models.CharField(max_length=100)
    industry = models.CharField(max_length=50)
    # noinspection PyTypeChecker
    company_size = models.CharField(max_length=10, choices=get_company_size)
    location = models.CharField(max_length=50)
    company_url = models.URLField(blank=True)
    description = models.TextField(blank=True)

    # Personal Data
    personal_photo = models.ImageField(
        blank=True, upload_to=employer_photo_path, validators=[file_validator]
    )
    role = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(
        max_length=20, validators=[validators.RegexValidator(r"^(\d{1,3})(\d{2})(\d{9})$")]
    )
    verified_id = models.BooleanField(default=False)
    last_update = models.DateTimeField(auto_now=True)

    def __repr__(self) -> str:
        return f"{self.user_id} - {self.company_name} - {self.role}"


class Job(BaseModel):
    work_schedules: Manager[WorkSchedules]
    employer_feedbacks: Manager[EmployerFeedback]
    worker_feedbacks: Manager[WorkerFeedback]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    title = models.CharField(max_length=255)
    employer = models.ForeignKey(
        to=EmployerAccount, null=True, on_delete=models.SET_NULL, related_name="jobs"
    )
    start_date = models.DateField(validators=[MinValueValidator(limit_value=date.today())])
    end_date = models.DateField(
        blank=True, null=True, validators=[MinValueValidator(limit_value=date.today())]
    )
    description = models.TextField()
    location = models.CharField(max_length=255)
    types = models.JSONField(validators=[app_validators.validate_job_types])
    shifts = models.JSONField(validators=[app_validators.validate_shifts])
    responsibilities = models.JSONField(default=list)
    qualifications = models.JSONField(default=list)
    benefits = models.JSONField(default=list)
    min_salary = models.FloatField(validators=[validators.MinValueValidator(0)])
    max_salary = models.FloatField(
        validators=[validators.MinValueValidator(0), validators.MaxValueValidator(100_000)]
    )
    period_salary = models.CharField(max_length=255)
    application_instructions = models.TextField()
    tags = models.JSONField(validators=[app_validators.validate_tags])
    applicants = models.ManyToManyField(to=WorkerAccount, related_name="applied_jobs")
    workers = models.ManyToManyField(to=WorkerAccount, related_name="jobs")
    done = models.BooleanField(default=False)
    posted_date = models.DateTimeField(auto_now_add=True)

    def __repr__(self) -> str:
        return f"{self.id} - {self.title}"


class Contract(BaseModel):
    class Status(models.TextChoices):
        PENDING = "PEN", _("Pending")
        ACTIVE = "ATV", _("Active")
        ENDED = "END", _("Ended")
        REJECTED = "RJT", _("Rejected")

    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    start_date = models.DateField(validators=[MinValueValidator(limit_value=date.today())])
    end_date = models.DateField(
        blank=True, null=True, validators=[MinValueValidator(limit_value=date.today())]
    )
    status = models.TextField(choices=Status.choices, default=Status.PENDING)
    signed_employer = models.ForeignKey(
        to=EmployerAccount, on_delete=models.SET_NULL, null=True, related_name="contracts"
    )
    signed_workers = models.ManyToManyField(
        to=WorkerAccount, related_name="signed_contracts", blank=True
    )


class FeedBack(BaseModel):
    class Meta:
        abstract = True

    rating = models.IntegerField(
        validators=[validators.MinValueValidator(0), validators.MaxValueValidator(5)]
    )
    text = models.TextField()


class EmployerFeedback(FeedBack):
    class Meta:
        constraints = [models.UniqueConstraint(fields=["job", "worker"], name="employer_feedback")]

    employer_id: int
    employer = models.ForeignKey(
        to=EmployerAccount, on_delete=models.SET_NULL, null=True, related_name="worker_feedbacks"
    )
    worker_id: int
    worker = models.ForeignKey(
        to=WorkerAccount, on_delete=models.SET_NULL, null=True, related_name="received_feedbacks"
    )
    job_id: int
    job = models.ForeignKey(
        to=Job, on_delete=models.SET_NULL, null=True, related_name="employer_feedbacks"
    )


class WorkerFeedback(FeedBack):
    class Meta:
        constraints = [models.UniqueConstraint(fields=["job", "employer"], name="worker_feedback")]

    worker_id: int
    worker = models.ForeignKey(
        to=WorkerAccount, on_delete=models.SET_NULL, null=True, related_name="job_feedbacks"
    )
    employer_id: int
    employer = models.ForeignKey(
        to=EmployerAccount, on_delete=models.SET_NULL, null=True, related_name="received_feedbacks"
    )
    job_id: int
    job = models.ForeignKey(

solution/forms.py
from uuid import uuid4

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import (
    gettext_lazy as _,
)

from solution.models import User

from .validators import UsernameEmailValidator


class UsernameEmailField(forms.CharField):
    def validate(self, value: str) -> None:
        """Validate username or email input"""
        super().validate(value)
        validate_username_email = UsernameEmailValidator()
        validate_username_email(value)


class LoginForm(forms.Form):
    email_username = UsernameEmailField()
    password = forms.CharField(min_length=3)


class RegisterForm(forms.Form):
    email = forms.EmailField()
    username = forms.CharField()
    password = forms.CharField(min_length=3)
    confirmation = forms.CharField(min_length=3)

    def clean_email(self):
        email: str = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise ValidationError(
                _("A user with this email already exists"),
                code="email_exists",
            )

        return email

    def clean_username(self):
        username: str = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            return f"{username}_{uuid4()}"

        return username

    def clean(self):
        cleaned_data = super().clean()

        password: str = cleaned_data["password"]
        confirmation: str = cleaned_data["confirmation"]

        if password != confirmation:
            error = ValidationError(
                _("Passwords must match."),
                code="password_mismatch",
            )

            self.add_error("password", error)
            self.add_error("confirmation", error)

        return cleaned_data

solution/views.py
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError
from django.http import HttpRequest
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

# from django.contrib.auth.decorators import login_required
# from django.utils.decorators import method_decorator
from solution.forms import LoginForm, RegisterForm
from solution.models import User


class AuthHttpRequest(HttpRequest):
    user: User


class IndexView(TemplateView):
    template_name: str = "solution/index.html"

    def get(self, request: AuthHttpRequest):
        if request.user.is_authenticated:
            user_data = {
                "firstName": request.user.first_name,
                "lastName": request.user.last_name,
                "username": request.user.username,
                "authenticated": request.user.is_authenticated,
                # "hasAccount": request.user.has_account,
            }
        else:
            user_data = {
                "firstName": None,
                "lastName": None,
                "username": request.user.username,
                "authenticated": request.user.is_authenticated,
                "hasAccount": False,
            }
        context = {"user_data": user_data}

        return render(request, self.template_name, context)


class RegisterView(TemplateView):
    template_name = "solution/register.html"

    def post(self, request: HttpRequest):
        form = RegisterForm(request.POST)

        if form.is_valid():
            email: str = form.cleaned_data["email"]
            password: str = form.cleaned_data["password"]
            username: str = form.cleaned_data["username"]

            try:
                user: User = User.objects.create_user(
                    username=username, email=email, password=password
                )
                user.user_permissions.clear()

                login(request=request, user=user)
                return redirect("solution:index")

            except ValidationError:
                return render(
                    request,
                    self.template_name,
                    {"form_errors": form.errors, "fields": form.cleaned_data},
                )
        else:
            return render(
                request,
                self.template_name,
                {"form_errors": form.errors, "fields": form.cleaned_data},
            )


class LoginView(TemplateView):
    template_name: str = "solution/login.html"

    def post(self, request: HttpRequest):
        form = LoginForm(request.POST)

        if form.is_valid():
            email = request.POST.get("email_username")
            username = email.split("@")[0]
            password = request.POST.get("password")

            user = authenticate(request=request, username=username, password=password)

            if user is not None:
                login(request=request, user=user)
                return redirect("solution:index")

            return render(request, self.template_name, {"auth_error": "Invalid Credentials"})

        return render(
            request, self.template_name, {"form_errors": form.errors, "fields": form.cleaned_data}
        )


def logout_view(request: HttpRequest):
    logout(request)
    return redirect("solution:index")

solution/templates/solution/index.html
{% extends 'solution/layout.html' %}

{% load django_vite %}
{% load static %}

{% block scripts %}
  {% vite_react_refresh %}
  {% vite_hmr_client %}
  {% vite_asset "src/main.tsx" %}
  {{ user_data|json_script:"userData" }}
{% endblock scripts %}

{% block body %}
  <div id="root"></div>
{% endblock body %}

solution/templates/solution/layout.html
{% load static %} {% load django_vite %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block styles %} {% endblock styles %} {% vite_asset "src/bootstrap.ts" %}
    {% block scripts %} {% endblock scripts %}

    <title>Solution</title>
  </head>
  <body>
    {% block body %} {% endblock body %} {% csrf_token %}
  </body>
</html>

solution/templates/solution/login.html
{% extends "solution/layout.html" %}

{% load static %}

{% block body %}
  <div id="login-page" class="container">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title text-center">Solution</h4>
        {% if auth_error %}
          <div class="alert alert-danger text-center">{{ auth_error }}</div>
          <div>Teste</div>
          <div>Teste</div>
        {% endif %}
        {# <div class="alert alert-danger text-center">{{ form_errors.email_username|join:" " }}</div>#}
        <form action="{% url 'solution:login' %}"
              method="post"
              class="needs-validation mb-3"
              novalidate>
          {% csrf_token %}
          <div class="mb-3">
            <label for="email_username" class="form-label">Username/Email Address</label>
            <input type="text"
                   class="form-control {{ form_errors.email_username|yesno:"is-invalid,,is-valid" }}"
                   name="email_username"
                   id="email_username"
                   placeholder="email@email.com"
                   aria-describedby="email_usernameValidation"
                   aria-live="polite"
                   required
                   value="{{ fields.email }}" />
            <div id="email_usernameValidation" class="invalid-feedback" aria-live="polite">
              {{ form_errors.email_username|join:" " }}
            </div>
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password"
                   class="form-control {{ form_errors.password|yesno:"is-invalid,,is-valid" }}"
                   name="password"
                   id="password"
                   aria-describedby="passwordValidation"
                   aria-live="polite"
                   autocomplete="current-password"
                   required />
            <div id="passwordValidation" class="invalid-feedback" aria-live="polite">
              {{ form_errors.password|join:" " }}
            </div>
          </div>
          <div class="d-flex justify-content-center">
            <input class="btn btn-primary" type="submit" value="Login" />
          </div>
        </form>
        Don't have an account? <a href="{% url 'solution:register' %}">Register here.</a>
      </div>
    </div>
  </div>
{% endblock body %}

solution/templates/solution/register.html
{% extends "solution/layout.html" %}

{% load static %}

{% block scripts %}
  <script type="module">
    const email = document.querySelector("#email");
    const username = document.querySelector("#username");
    email.addEventListener("input", () => {
      username.value = email.value.split("@")[0];
    });
  </script>
{% endblock scripts %}

{% block body %}
  <div id="register-page" class="container auth-container">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title text-center">Solution</h4>
        <form action="{% url 'solution:register' %}"
              method="post"
              class="needs-validation mb-3"
              novalidate>
          {% csrf_token %}
          <div class="mb-3">
            <label for="email" class="form-label">Email Address</label>
            <input type="email"
                   class="form-control {{ form_errors.email|yesno:"is-invalid,,is-valid" }}"
                   name="email"
                   id="email"
                   placeholder="email@email.com"
                   aria-describedby="emailValidation"
                   aria-live="polite"
                   autocomplete="email"
                   required
                   value="{{ fields.email }}" />
            <small class="text-muted">Username from the provided e-mail will be used as default
            username. You can change it later in account settings</small>
            <div id="emailValidation" class="invalid-feedback" aria-live="polite">
              {{ form_errors.email|join:" " }}
            </div>
            <input type="hidden" name="username" id="username">
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password"
                   class="form-control {{ form_errors.password|yesno:"is-invalid,,is-valid" }}"
                   name="password"
                   id="password"
                   aria-describedby="passwordValidation"
                   aria-live="polite"
                   autocomplete="new-password"
                   required />
            <div id="passwordValidation" class="invalid-feedback" aria-live="polite">
              {{ form_errors.password|join:" " }}
            </div>
          </div>
          <div class="mb-3">
            <label for="confirmation" class="form-label">Password Confirmation</label>
            <input type="password"
                   class="form-control {{ form_errors.confirmation|yesno:"is-invalid,,is-valid" }}"
                   name="confirmation"
                   id="confirmation"
                   aria-describedby="passwordValidation"
                   aria-live="polite"
                   autocomplete="new-password"
                   required />
            <div id="confirmationValidation" class="invalid-feedback" aria-live="polite">
              {{ form_errors.confirmation|join:", " }}
            </div>
          </div>
          <input class="btn btn-primary" type="submit" value="Register" />
        </form>
        Already have an account? <a href="{% url 'solution:login' %}">Log In here.</a>
      </div>
    </div>
  </div>
{% endblock body %}

solution/templates/solution/swagger-ui.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui.css" />
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui.css" />
    <title>SwaggerUI</title>
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui-bundle.js" crossorigin></script>
    <script src="https://unpkg.com/swagger-ui-dist@4.5.0/swagger-ui-standalone-preset.js"
            crossorigin></script>
    <script>
      window.onload = () => {
        window.ui = SwaggerUIBundle({
          url: "{% url schema_url %}",
          dom_id: '#swagger-ui',
          presets: [
            SwaggerUIBundle.presets.apis,
            SwaggerUIStandalonePreset
          ],
          layout: "BaseLayout",
          requestInterceptor: (request) => {
            request.headers['X-CSRFToken'] = "{{ csrf_token }}"
            return request;
          }
        });
      };
    </script>
  </body>
</html>